services:
  spg_images:
    image: pg_steam
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: Europe/Berlin
    volumes:
      - ./output:/app/output
    ports:
      - 9898:9898